crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.products, name='products'),
    path('create', views.create_product, name='create_product'),
    path('update/<int:pk>', views.update_product, name="update_product"),
    path('delete/<int:pk>', views.delete_product, name="delete_product"),
]

home/models.py
from django.db import models

PRODUCT_TYPE = (
    ('electronics', 'Electronics'),
    ('medical', 'Medical'),
    ('fashion', 'Fashion'),
    ('food', 'Food'),
    ('books', 'Books'),
    ('sports', 'Sports')
)

STATUS = (
    (0, 'Unavailable'),
    (1, 'Available'),
)

# Create your models here.
class Product(models.Model):
    """
    Product model representing products of different categories
    """
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.IntegerField(choices=STATUS, default=1)
    category = models.CharField(choices=PRODUCT_TYPE, max_length=200)
    date_created = models.DateField(auto_now_add=True)
    date_updated = models.DateField(auto_now=True)

    def __str__(self):
        """
            Returns a string representation of the Product instance.

            The string format is: "<name> [<category>]"

            Returns:
                str: A string that represents the product with its name and category.

            Example:
                product = Product.objects.create(
                    name="Test Product",
                    category="Electronics",
                    price=100.00,
                    status=1
                )
                print(product)
            Output: Test Product [Electronics]

        """
        return f"{self.name} [{self.category}]"

home/views.py
from django.shortcuts import render, get_object_or_404, redirect
from home.models import Product, PRODUCT_TYPE, STATUS


# Create your views here.

def products(request):
    """
    Retrieve all products from the database and pass them to the template for display.

    Args:
        request: The HTTP request object.

    Returns:
        A rendered template displaying the list of all products.
    """
    product_list = Product.objects.all()

    return render(request, 'products.html', {'products': product_list})


def create_product(request):
    """
    Handle the creation of a new product. If the request method is POST,
    it will create a new product and redirect to the product list page.

    Args:
        request: The HTTP request object.

    Returns:
        A rendered template for creating a new product or a redirect to the product list.
    """
    if request.method == "POST":
        name = request.POST.get('name')
        category = request.POST.get('category')
        price = request.POST.get('price')
        status = request.POST.get('status')

        # Select Category based on value
        for pt in PRODUCT_TYPE:
            if pt[0] == category:
                category = pt[1]
                break

        # Create a new product instance and save it
        product = Product.objects.create(
            name=name,
            category=category,
            price=price,
            status=status
        )

        return redirect('products')

    return render(request, 'create-product.html', {'product_type': PRODUCT_TYPE, 'status': STATUS})


def update_product(request, pk):
    """
    Update an existing product based on its primary key (pk). If the request method is POST,
    the product will be updated and the user will be redirected to the product list page.

    Args:
        request: The HTTP request object.
        pk: The primary key of the product to be updated.

    Returns:
        A rendered template for updating the product or a redirect to the product list.
    """
    try:
        product = Product.objects.get(pk=pk)
    except Product.DoesNotExist:
        # Redirect to 404.html explicitly
        return render(request, '404.html', status=404)

    if request.method == "POST":
        name = request.POST.get('name')
        category = request.POST.get('category')
        price = request.POST.get('price')
        status = request.POST.get('status')

        # Select Category based on value
        for pt in PRODUCT_TYPE:
            if pt[0] == category:
                category = pt[1]
                break

        # Update the product with the new data
        product.name = name
        product.category = category
        product.price = price
        product.status = status

        # Save the updated product to the database
        product.save()

        return redirect('products')

    return render(request, 'update-product.html', {'product': product, 'product_type': PRODUCT_TYPE, 'status': STATUS})


def delete_product(request, pk):
    """
    Delete an existing product based on its primary key (pk). If the request method is POST,
    the product will be deleted and the user will be redirected to the product list page.

    Args:
        request: The HTTP request object.
        pk: The primary key of the product to be deleted.

    Returns:
        A redirect to the product list page after deletion.
    """
    try:
        product = Product.objects.get(pk=pk)
    except Product.DoesNotExist:
        # Redirect to 404.html explicitly
        return render(request, '404.html', status=404)

    if request.method == "POST":
        product.delete()
        return redirect('products')
    else:
        return redirect('products')

home/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Products</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'products' %}">Products</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'products' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'create_product' %}">Create</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
        {% block content%}

        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
            integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

home/templates/create-product.html
{% include 'base.html' %}
{% block content %}
<div class="container col-4">
    <h3 class="mt-3">Create Product</h3>
    <form class="mt-3" method="post">
        {% csrf_token %}

        <div class="col-md">
            <div class="form-floating">
                <select class="form-select border-4" id="floatingCategoryGrid" name="category">
                    {% for pt in product_type %}
                        <option value= {{pt.0}} > {{pt.1}} </option>
                    {% endfor %}
                </select>
                <label for="floatingCategoryGrid">Product Category</label>
            </div>
        </div>

        <div class="mt-3">
            <label for="name" class="form-label">Product Name</label>
            <input type="text" class="form-control border-4" id="name" name="name" required>
        </div>

        <div class="row g-2 mt-3">
            <div class="col-md">
                <div class="form-floating">
                    <input type="number" class="form-control border-4" id="price" name="price" min="0" step="0.01" value="0.00" required>
                    <label for="price">Price</label>
                </div>
            </div>
            <div class="col-md">
                <div class="form-group">
                    <div class="form-floating" >
                        <select class="form-select border-4" id="floatingStatusGrid" name="status">
                            {% for s in status %}
                                <option value= {{s.0}} > {{s.1}} </option>
                            {% endfor %}
                        </select>
                        <label for="floatingStatusGrid">Product Status</label>
                    </div>
                </div>
            </div>
        </div>

        <div class="mt-3">
            <button class="btn btn-primary btn-lg" type="submit"> Submit </button>
        </div>

    </form>

</div>
{% endblock %}

home/templates/products.html
{% extends 'base.html' %}
{% block content %}

<div class="mb-3">
    <center>
        <h3> Products</h3>
    </center>
</div>

<table class="table">
  <thead>
    <tr class="table-dark">
      <th scope="col">Category</th>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th scope="col">Update</th>
      <th scope="col">Delete</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
    {% for product in products %}
        <tr>
            <td>{{ product.get_category_display }}</td>
            <td>{{ product.name }}</td>
            <td>{{ product.price }}</td>
            <td>
                <a href="{% url 'update_product' product.id %}" class="btn btn-primary btn-sm">Update</a>
            </td>
            <td>
                <form action="{% url 'delete_product' product.id %}" method="post" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                </form>
            </td>
            {% if product.status == 0 %}
                <td class="table-danger">{{ product.get_status_display }}</td>
            {% endif %}
            {% if product.status == 1 %}
                <td class="table-success">{{ product.get_status_display }}</td>
            {% endif %}
        </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

home/templates/update-product.html
{% include 'base.html' %}
{% block content %}

<div class="container col-4">
    <h3 class="mt-3">Update Product</h3>
    <form class="mt-3" method="post">
        {% csrf_token %}

        <div class="col-md">
            <div class="form-floating">
                <select class="form-select border-4" id="floatingCategoryGrid" name="category" value= {{ product.category }}>
                    {% for pt in product_type %}
                        <option value="{{ pt.0 }}" {% if pt.1 == product.category %} selected {% endif %}>
                            {{ pt.1 }}
                        </option>
                    {% endfor %}
                </select>
                <label for="floatingCategoryGrid">Product Category</label>
            </div>
        </div>

        <div class="mt-3">
            <label for="name" class="form-label">Product Name</label>
            <input type="text" class="form-control border-4" id="name" name="name" value = "{{ product.name }}">
        </div>

        <div class="row g-2 mt-3">
            <div class="col-md">
                <div class="form-floating">
                    <input type="number" class="form-control border-4" id="price" name="price" min="0" step="0.01" value="{{ product.price }}">
                    <label for="price">Price</label>
                </div>
            </div>
            <div class="col-md">
                <div class="form-group">
                    <div class="form-floating" >
                        <select class="form-select border-4" id="floatingStatusGrid" name="status">
                            {% for s in status %}
                                <option value="{{ s.0 }}" {% if s.0 == product.status %} selected {% endif %}>
                                    {{ s.1 }}
                                </option>
                            {% endfor %}
                        </select>
                        <label for="floatingStatusGrid">Product Status</label>
                    </div>
                </div>
            </div>
        </div>

        <div class="mt-3">
            <button class="btn btn-primary btn-lg" type="submit"> Update </button>
        </div>

    </form>

</div>
{% endblock %}